before_deploy:
  - tnpm i tnpm@release-3
  - ./node_modules/.bin/tnpm install
  - ./node_modules/.bin/tnpm update
  - ./node_modules/.bin/tnpm run site
options:
  branch: 'master'
  dist: '_site'
cname: 'beta.antm.alipay.net'